---
- name: test my new module
  hosts: localhost
  tasks:
  - name: run the new module
    opensds_volumes:
      action: create 
      name: 'new_vol1'
      size: 1
      description: "THis is for volume creation"
      availability_zone: "default"
      output: {}
      vol_id: "08cc636c-ea6c-4a16-aed6-0886c33926a1"
      new: true
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
